<?php
    $locale = isset($_GET["lang"]) ? $_GET["lang"] : 'en';
    
    // begins with http -> absolute, else relative
    $endpoint = isset($_REQUEST['endpoint']) ? $_REQUEST['endpoint'] : '/sparql';
    
    // empty means use it all
    $graph    = isset($_REQUEST['default-graph-uri']) ? $_REQUEST['default-graph-uri'] : '';
    
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html class="js" lang="en" dir="ltr" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
        <title>European Commission | Opening up European Commission</title>
        
        <style media="all" type="text/css">@import "style.css";</style>

        <script type="text/javascript" src="lib/gettext/0.08/lib/Gettext.js"></script>

        <link id="active_lang" rel="gettext" type="application/x-po"
            href="src/main/resources/i18n/<?php echo $locale ?>/LC_MESSAGES/messages.po" />

        <script type="text/javascript"
            src="lib/namespacedotjs/a28da387ce/Namespace.js"></script>

        <script type="text/javascript" src="lib/jquery/1.6.2/jquery-1.6.2.js"></script>

        <script type="text/javascript"
            src="lib/jquery-ui/1.8.16/ui/jquery-ui.js"></script>
        <script type="text/javascript"
            src="lib/jquery-ui/1.8.16/external/jquery.cookie.js"></script>

        <script type="text/javascript"
            src="lib/dynatree/1.2.0_rc1/src/jquery.dynatree.js"></script>

        <link rel='stylesheet' type='text/css'
            href='lib/dynatree/1.2.0_rc1/src/skin/ui.dynatree.css'>
        
        <link rel="stylesheet" type="text/css"
            href="src/main/javascript/style.css" />

        <script type="text/javascript"
            src="lib/underscore/1.3.1/underscore.js"></script>

        <script type="text/javascript" src="lib/backbone/0.5.3/backbone.js"></script>

        <script type="text/javascript" src="lib/agility/0.1.2/agility.min.js"
            charset="utf-8"></script>

	<!-- Open Layers 2.11-rc2 -->
	<script type="text/javascript"
		src="lib/open-layers/2.10/OpenLayers.js"></script>

	<script type="text/javascript"
		src="lib/rdfquery/1.0/jquery.rdfquery.core-1.0.js"></script>

	<script type="text/javascript"
		src="http://www.openstreetmap.org/openlayers/OpenStreetMap.js"></script>

	<!-- Configuration files -->
	<script type="text/javascript"
		src="src/main/javascript/ssb.namespacePrefixes.js"></script>

	<!-- The actual spatial semantic browsing widgets -->
	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/collections/QuadTree.js"></script>
    
	<script type="text/javascript"
		src="src/main/javascript/backend/ssb.backend.quadtree.js"></script>

	<script type="text/javascript" 
		src="src/main/javascript/ssb.utils.js"></script>

	<script type="text/javascript" 
		src="src/main/javascript/Dispatcher.js"></script>
    
	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/collections/MultiMap.js"></script>
    
	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/collections/MultiGraph.js"></script>
    
	<script type="text/javascript"
		src="src/main/javascript/jsonrdf-extraction-utils.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/facet-controller.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/jquery.ssb.facets.js"></script>
    
	<script type="text/javascript"
		src="src/main/javascript/jquery.ssb.instances.js"></script>
    
	<script type="text/javascript"
		src="src/main/javascript/jquery.ssb.map.js"></script>
    
	<script type="text/javascript"
		src="src/main/javascript/jquery.ssb.search.js"></script>
    
	<script type="text/javascript"
		src="src/main/javascript/jquery.ssb.facts.js"></script>
    
	<script type="text/javascript"
		src="src/main/javascript/jquery.ssb.browsebox.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/query-factory/ssb.query-factory.linkedgeodata.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/backend/SparqlServiceVirtuoso.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/backend/ssb.backend.delay.js"></script>
    
	<script type="text/javascript"
		src="src/main/javascript/backend/ssb.backend.virtuoso.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/backend/utils.sparql.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/sparql/Syntax.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/vocabs/xsd.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/vocabs/rdf.js"></script>
    
	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/vocabs/rdfs.js"></script>
    
	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/vocabs/wgs84.js"></script>
    
	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/vocabs/geovocab.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/facets/Facets.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/facets/Constraints.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/facets/QueryUtils.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/facets/facets-old.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/facets/constraints.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/utils/StringUtils.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/utils/LabelFetcher.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/utils/RdfQuery.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/utils/TalisJson.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/widgets/FacetBox.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/widgets/ResourceWidget.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/app/controllers/AppController.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/app/QueryGenerator.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/query-factory/ssb.query-factory.wgs84.js"></script>
		
        <script type="text/javascript"
		src="src/main/javascript/backend/ssb.backend.wgs84.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/collections/QuadTreeModel.js"></script>
		
        <script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/collections/QuadTreeCache.js"></script>

	<!-- Layouting for this (p)HTML file-->
	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/app/Layout.js"></script>


	<script type="text/javascript">
            var ssbconf = {};
            
            ssbconf.endpoint = '<?php echo $endpoint ?>';
            ssbconf.models = ['<?php echo $graph ?>'];

            var lang = '<?php echo $locale ?>';

            function insertParam(key, value)
            {
                key = escape(key); value = encodeURIComponent(value);

                var kvp = document.location.search.substr(1).split('&');

                var i=kvp.length; var x; while(i--) 
                {
                    x = kvp[i].split('=');

                    if (x[0]==key)
                    {
                            x[1] = value;
                            kvp[i] = x.join('=');
                            break;
                    }
                }

                if(i<0) {kvp[kvp.length] = [key,value].join('=');}

                //this will reload the page, it's likely better to store this until finished
                document.location.search = kvp.join('&'); 
            }
        
        </script>

	<!-- <script type="text/javascript" src="src/main/javascript/main.js"></script>  -->
	<script type="text/javascript" src="src/main/javascript/main.js"></script>
	
	<script type="text/javascript">
	
	    $(document).ready(function(){ 
            $("#tabs-instances").click ( function () {
                $("#tabs-facets-content").hide ();
                $("#tabs-places-content").hide ();
                $("#tabs-types-content").hide ();
                
                $("#tabs-instances-content").show ();
            });
            $("#tabs-facets").click ( function () {
                $("#tabs-instances-content").hide ();
                $("#tabs-types-content").hide ();
                $("#tabs-places-content").hide ();
                
                $("#tabs-facets-content").show ();
            });
            $("#tabs-types").click ( function () {
                $("#tabs-instances-content").hide ();
                $("#tabs-facets-content").hide ();
                $("#tabs-places-content").hide ();
                
                $("#tabs-types-content").show ();
            });
            $("#tabs-places").click ( function () {
                $("#tabs-instances-content").hide ();
                $("#tabs-facets-content").hide ();
                $("#tabs-types-content").hide ();
                
                $("#tabs-places-content").show ();
            });
            
            $("#tabs-instances-content").hide ();
            $("#tabs-places-content").hide ();
            $("#tabs-types-content").hide ();
            
            $("#box-facts-closebutton-img").click(function () {
                $("#box-facts").fadeOut ('slow');
            });
	    });
	
	</script>

    </head>
    <body>
	<div id="wrapper">
	    <div id="header">
		<img src="images/logo_european_commision.gif" id="header-logo"/>
		<div id="header-headline">
		    <a href="">Open Data Portal</a>
		</div>
		<div id="header-abstract">
		    Spatial Browser
		</div>
		<div id="header-menu-right">
		    <a href="#"><span id="org.ec.odp.ssb.ui.label.legal-notice">Legal Notice</span></a> | <a href="#"><span id="org.ec.odp.ssb.ui.label.contact">Contact</span></a> | <a href="#"><span id="org.ec.odp.ssb.ui.label.search">Search</span></a> 
		    <select name="lang" id="language-switcher">
			<option value="#">Čeština</option>
			<option value="#">Dansk</option>
			<option value="de">Deutsch</option>
			<option value="#">Ελληνικά</option>
			<option value="en" selected="selected">English</option>
			<option value="#">Eesti</option>
			<option value="#">Español</option>
			<option value="#">Français</option>
			<option value="#">Gaeilge</option>
		    </select>
		</div>
		<div id="header-blueblock">&nbsp;</div>
	    </div>        
	    
	    <div id="main">
		<div id="map"></div>

		<div id="tabs">
		    
		    <div id="tabs-links">
                <a id="tabs-instances">
                    <div id="org.aksw.ssb.ui.label.instances-tab">Instances</div></a>
                <a id="tabs-facets">
                    <div id="org.aksw.ssb.ui.label.facets-tab">Facets</div></a>
                <a id="tabs-types">
                    <div id="org.aksw.ssb.ui.label.types-tab">Types</div></a>
                <a id="tabs-places">
                    <div id="org.aksw.ssb.ui.label.places-tab">Places</div></a>
            </div>
            
            <br/>
		    
		    <div id="tabs-instances-content">
                <div class="tabdiv" id="instances-tab">
                    <div id="instances"></div>
                </div>
		    </div>
		    <div id="tabs-facets-content">
                <div class="tabdiv" id="facets-tab"></div>
		    </div>
		    <div id="tabs-types-content">
                <div class="tabdiv" id="types-tab">
                    <form>
                        <input type="radio" name="type" value="http://ssb.org/facet/project"/> Projects
                        <input type="radio" name="type" value="http://ssb.org/facet/subvention"/> Subventions
                    </form>
                </div>
		    </div>
		    <div id="tabs-places-content">
                <div>
                    <div class="tabdiv" id="places-tab">
                        <div style="float: left;">
                        <form id="box-places-searchform" action="javascript: doSearch();">
                            <input type="text" id="search-field" name="search-field" value="Leipzig" autocomplete="off"/>
                            <input type="image" src="images/search.png" class="icon"/>
                        </form>
                        </div>
                        <p style="font-size:7px;">
                            powered by
                            <a href="http://nominatim.openstreetmap.org" target="_blank">Nominatim</a>
                        </p>		    
                        <div id="searchResults"></div>
                    </div>
                </div>
		    </div>
		    
		</div>

		<div id="box-facts">
            <div id="box-facts-closebutton">
                <img src="images/cross.svg" id="box-facts-closebutton-img"/>
            </div>
        </div>
		
	    </div>
    
	</div>
    </body>
</html>
