<?php
    $locale = isset($_GET["lang"]) ? $_GET["lang"] : 'en';
    
    // begins with http -> absolute, else relative
    $endpoint = isset($_REQUEST['endpoint']) ? $_REQUEST['endpoint'] : '/sparql';
    
    // empty means use it all
    $graph    = isset($_REQUEST['default-graph-uri']) ? $_REQUEST['default-graph-uri'] : '';
    
    
    $endpoint = "http://localhost/sparql";
    // LGD-TEST
    //$endpoint = "http://localhost/lgd/sparql";
    
    
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html class="js" lang="en" dir="ltr" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">

        <script type="text/javascript"
            src="lib/namespacedotjs/a28da387ce/Namespace.js"></script>

        <script type="text/javascript" src="lib/jquery/1.7.2/jquery-1.7.2.js"></script>

        <script type="text/javascript"
            src="lib/underscore/1.3.1/underscore.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/backend/SparqlServiceVirtuoso.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/backend/ssb.backend.delay.js"></script>
    
	<script type="text/javascript"
		src="src/main/javascript/backend/ssb.backend.virtuoso.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/backend/utils.sparql.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/sparql/Syntax.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/vocabs/xsd.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/vocabs/rdf.js"></script>
    
	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/vocabs/rdfs.js"></script>
    
	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/vocabs/owl.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/vocabs/wgs84.js"></script>
    
	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/vocabs/geovocab.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/vocabs/appvocab.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/facets/Facets.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/facets/Constraints.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/facets/QueryGenerationUtils.js"></script>

	<script type="text/javascript"
		src="src/main/javascript/org/aksw/ssb/facets/QueryExecutionUtils.js"></script>

	
	<script type="text/javascript">

		/*
		 * Fetch named graphs
		 */		
    	$(document).ready(function() {

    		var backend = Namespace("org.aksw.ssb.backend");
	    	var queryUtils = Namespace("org.aksw.ssb.facets.QueryUtils");

	    	var service = new backend.SparqlServiceVirtuoso("http://localhost/sparql", "");
	    	queryUtils.fetchClasses(service).pipe(function(classes) {
		    	console.log("Classes:", classes);
	    	});    		
    	});


		/*
		 * Fetch classes
		 */
    	$(document).ready(function() {

    		var backend = Namespace("org.aksw.ssb.backend");
	    	var queryUtils = Namespace("org.aksw.ssb.facets.QueryUtils");

	    	var tmp = new backend.SparqlServiceVirtuoso("http://localhost/sparql", "");
			var service = new backend.SparqlServicePaginator(tmp, 1000);

	    	queryUtils.fetchNamedGraphs(service).pipe(function(graphNames) {
		    	console.log("Named graphs:", graphNames);
	    	});
    		
        	
    	});
    	
    	
	    $(document).ready(function() {

	    	/*
	    	 * A test that uses SPARQL pagination
	    	 */
		    
	    	var sparql = Namespace("org.aksw.ssb.sparql.syntax");
	    	var backend = Namespace("org.aksw.ssb.backend");
	    	var rdf = Namespace("org.aksw.ssb.vocabs.rdf");
	    	
	    	var query = new sparql.Query();
			var s = sparql.Node.v("s");
			var p = rdf.type; //sparql.Node.v("p");
			var o = sparql.Node.v("o");
	    	
	    	query.isResultStar = true;
	    	query.elements.push(new sparql.ElementTriplesBlock([new sparql.Triple(s, p, o)])); 
			query.limit = 10000;
	    	
	    	var tmp = new backend.SparqlServiceVirtuoso("http://localhost/sparql", "");
			var service = new backend.SparqlServicePaginator(tmp, 1000);

	    	$.when(service.executeSelect(query)).then(function(talisRdfJson) {
		    	alert("size: " + talisRdfJson.results.bindings.length);
	    	});
			
	    });	
	</script>

    </head>
    <body>
	
    </body>
</html>
