#!/bin/sh -e
# postinst script for ontowiki-virtuoso
#
# see: dh_installdeb(1)

echo "---- starting postinst $@"


### APACHE CONFIG

a2enmod proxy
a2enmod proxy_http
service apache2 restart



echo "---- ending postinst $@"
